version: '3'
services:
    laravel:
        container_name: 'docker_php'
        image: tangramor/nginx-php8-fpm
        environment:
            TZ: 'Asia/Tokyo'
            WEBROOT: '/var/www/html/public'
            PHP_REDIS_SESSION_HOST: 'redis'
            CREATE_LARAVEL_STORAGE: '1'
            COMPOSERMIRROR: 'https://mirrors.cloud.tencent.com/composer/'
            NPMMIRROR: 'https://registry.npm.taobao.org'
        ports:
            - '${APP_PORT:-80}:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/html'
            - './infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './infra/docker/nginx/logs:/var/log/nginx'
            - './infra/docker/php/php.ini:/usr/local/etc/php/php.ini'
        volumes_from:
            - mysql
        networks:
            - internal
        depends_on:
            - mysql
        restart: '${DOCKER_RESTART}'
    cron:
        container_name: 'docker_cron'
        build: ./infra/docker/cron
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
        restart: '${DOCKER_RESTART}'
    mysql:
        container_name: 'docker_mysql'
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'db-mysql:/var/lib/mysql'
            - './export:/var/lib/mysql-files'
            - ./infra/docker/mysql/my.cnf:/etc/my.cnf
        networks:
            - internal
        restart: '${DOCKER_RESTART}'
    phpmyadmin:
        container_name: 'docker_phpmyadmin'
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        ports:
            - '${PHPMYADMIN_PORT:-8080}:80'
        volumes:
            - ./infra/docker/phpmyadmin/sessions:/sessions
            - ./infra/docker/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php
        networks:
            - internal
        depends_on:
            - mysql
networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/27
volumes:
    db-mysql:
        driver: local
