version: '3'
services:
  web:
    image: nginx:1.20
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    
  app:
    build: ./infra/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    env_file: .env_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
