version: '3'
services:
  web:
    image: nginx:1.20
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    links:
      - app
      - mysql
    
  app:
    build: ./infra/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    env_file: .env_db
    command: --default-authentication-plugin=mysql_native_password  --default-time-zone=Asia/Tokyo
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./infra/db/mysql/volumes:/var/lib/mysql
      - ./mysqlexport:/var/lib/mysql-files

