version: '3'
services:
    laravel:
        container_name: 'docker_php'
        image: tangramor/nginx-php8-fpm
        environment:
            TZ: 'Asia/Tokyo'
            WEBROOT: '/var/www/html/public'
            PHP_REDIS_SESSION_HOST: 'redis'
            COMPOSERMIRROR: 'https://packagist.org'
            NPMMIRROR: 'https://registry.npm.taobao.org'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - './laravel:/var/www/html'
            - './infra/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './infra/docker/nginx/logs:/var/log/nginx'
            - './infra/docker/php/php.ini:/usr/local/etc/php/php.ini'
        volumes_from:
            - mysql
        networks:
            - internal
        depends_on:
            - mysql
        restart: '${DOCKER_RESTART}'
    cron:
        container_name: 'docker_cron'
        build: ./infra/docker/cron
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - internal
        restart: '${DOCKER_RESTART}'
    mysql:
        container_name: 'docker_mysql'
        image: mysql:8.0
        ports:
            - '3306:3306'
        command:
            mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        environment:
            TZ: 'Asia/Tokyo'
            MYSQL_ROOT_PASSWORD: password
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - 'db-mysql:/var/lib/mysql'
            - './export:/var/lib/mysql-files'
        networks:
            - internal
        restart: '${DOCKER_RESTART}'
    phpmyadmin:
        container_name: 'docker_phpmyadmin'
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
        ports:
            - '${PHPMYADMIN_PORT:-8080}:80'
        volumes:
            - ./infra/docker/phpmyadmin/sessions:/sessions
        networks:
            - internal
        depends_on:
            - mysql
networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.0/27
volumes:
    db-mysql:
        driver: local
